name: 'Jenkis Slave Release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        type: string
        required: true

jobs:
  prepare:
    runs-on: ubuntu-18.04
    outputs:
      version_tag: ${{ steps.version_tag.outputs.value }}
      build_date: ${{ steps.build_date.outputs.value }}
    steps:
      - name: Format version tag
        shell: bash
        id: version_tag
        env:
          INPUT_TAG: ${{ github.event.inputs.version }}
        run: |
          TAG=${INPUT_TAG#v}
          echo "::set-output name=value::$TAG"
      - name: Build date
        shell: bash
        id: build_date
        run: echo "::set-output name=value::$(date +%FT%T%z)"

  docker:
    needs:
      - prepare
    env:
      SERVICE: jenkins-slave
      VERSION_TAG: ${{ needs.prepare.outputs.version_tag }}
      BUILD_DATE: ${{ needs.prepare.outputs.build_date }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ env.SERVICE }}-buildx

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ env.VERSION_TAG }}
            GIT_HASH=${{ github.sha }}
            BUILD_DATE=${{ env.BUILD_DATE }}
          labels: |
            org.label-schema.schema-version=1.0
            org.label-schema.vcs-ref=${{ github.sha }}
            org.label-schema.version=${{ env.VERSION_TAG }}
            org.label-schema.name=${{ env.SERVICE }}
          tags: |
            vietanhs0817/${{ env.SERVICE }}:latest
            vietanhs0817/${{ env.SERVICE }}:${{ env.VERSION_TAG }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move Docker cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  release:
    needs:
      - prepare
      - docker
    runs-on: ubuntu-18.04
    env:
      VERSION_TAG: ${{ needs.prepare.outputs.version_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Create tag
        run: |
          git tag -d "$VERSION_TAG" 2> /dev/null || echo "Release tag '$VERSION_TAG' does NOT exist"
          git tag --annotate --message "ADPR $VERSION_TAG" "$VERSION_TAG"
          git push origin "refs/tags/$VERSION_TAG"

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          release_name: Jenkins slave ${{ env.VERSION_TAG }}
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
